name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: Nomadify
      Test_Project_Path: test/Nomadify.Tests/Nomadify.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore
    - name: Restore
      run: dotnet restore

    # Build
    - name: Build
      run: dotnet build --configuration Debug --nologo --no-restore

    # Test
    - name: Test
      run: dotnet test --configuration Debug --nologo --no-build
